In [79]:
import numpy as np
from random import randint

In [35]:
possible_responses = [
    "Hi, how are you?",
    "You are amazing",
    "I'm sure you will be fine, you are so intelligent!",
    "I love you",
    "Can we get married?"
]

In [9]:
how_many = 4
top_k_robots = 2
how_many_responses = len(possible_responses)

In [19]:
def generate_new() -> np.ndarray:
    robots = np.random.randint(0, how_many_responses, size=(how_many, how_many_responses))
    return robots

In [23]:
robots = generate_new()
robots

array([[3, 0, 3, 1, 0],
       [4, 2, 3, 2, 2],
       [0, 2, 4, 2, 0],
       [4, 1, 2, 0, 1]])

In [21]:
def test(robots):
    scores = []
    for i in range(how_many):
        robot = robots[i]
        print("Next converstation")
        for index in robot:
            my_text = input("You say: ")
            if my_text == "x":
                break
            print(possible_responses[index])
        rating = int(input("Rate: "))
        scores.append([robot, rating])

    return scores

In [60]:
lst_j = []
for j in range(robots.shape[0]):

    lst_i = np.array([])
    for i in robots[j]:
        lst_i  =np.append(lst_i, possible_responses[i])
    
    lst_j.append(lst_i)
lst_j = np.array(lst_j)
lst_j

array([['I love you', 'Hi, how are you?', 'I love you',
        'You are amazing', 'Hi, how are you?'],
       ['Can we get married?',
        "I'm sure you will be fine, you are so intelligent!",
        'I love you',
        "I'm sure you will be fine, you are so intelligent!",
        "I'm sure you will be fine, you are so intelligent!"],
       ['Hi, how are you?',
        "I'm sure you will be fine, you are so intelligent!",
        'Can we get married?',
        "I'm sure you will be fine, you are so intelligent!",
        'Hi, how are you?'],
       ['Can we get married?', 'You are amazing',
        "I'm sure you will be fine, you are so intelligent!",
        'Hi, how are you?', 'You are amazing']], dtype='<U50')

In [64]:
robots[0]

array([3, 0, 3, 1, 0])

In [65]:
ratings = [3, 5, 3, 2]
scores = []
for i in range(how_many):
    scores.append([robots[i], ratings[i]])
scores

[[array([3, 0, 3, 1, 0]), 3],
 [array([4, 2, 3, 2, 2]), 5],
 [array([0, 2, 4, 2, 0]), 3],
 [array([4, 1, 2, 0, 1]), 2]]

In [66]:
scores = sorted(scores, key=lambda pair:pair[1], reverse=True)

In [73]:
scores
best_robots = scores[0:top_k_robots]
best_robots

[[array([4, 2, 3, 2, 2]), 5], [array([3, 0, 3, 1, 0]), 3]]

In [71]:
robots = np.zeros((how_many, how_many_responses))
robots

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
for i in range(top_k_robots):
        robots[i] = best_robots[i][0]

In [75]:
robots

array([[4., 2., 3., 2., 2.],
       [3., 0., 3., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
robot = robots[0]
robot

array([4., 2., 3., 2., 2.])

In [77]:
def mutate(robot):
    idx = randint(0, how_many_responses - 1)
    robot[idx] = randint(0, how_many_responses - 1)
    return robot

In [80]:
mutate(robot)

array([4., 3., 3., 2., 2.])

In [81]:
how_many_responses

5